/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 18-May-2019 1:58:34 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

USE [EnglishStudyPro]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CategorizedVocabularies]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [CategorizedVocabularies]
GO

/* Create Tables */

CREATE TABLE [CategorizedVocabularies]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[hierarchical_category_id] bigint NOT NULL,
	[class] bigint NOT NULL,
	[vocabulary] nvarchar(128) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [CategorizedVocabularies] 
 ADD CONSTRAINT [PK_CategorizedVocabularies]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [CategorizedVocabularies] 
 ADD CONSTRAINT [UQ_CategorizedVocabularies_id] UNIQUE NONCLUSTERED ([id] ASC)
GO