/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 18-May-2019 1:58:34 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

USE [EnglishStudyPro]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Categories]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Categories]
GO

/* Create Tables */

CREATE TABLE [Categories]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[name] nvarchar(128) NOT NULL,
	[title] nvarchar(128) NOT NULL,
	[parent] bigint NULL DEFAULT 0
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Categories] 
 ADD CONSTRAINT [PK_Categories]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Categories] 
 ADD CONSTRAINT [UQ_Categories_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Categories] 
 ADD CONSTRAINT [UQ_Categories_name] UNIQUE NONCLUSTERED ([name] ASC)
GO

ALTER TABLE [Categories] 
 ADD CONSTRAINT [UQ_Categories_title] UNIQUE NONCLUSTERED ([title] ASC)
GO