/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 18-May-2019 1:58:31 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

USE [EnglishStudyPro]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Categories]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Categories]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[CategorizedVocabularies]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [CategorizedVocabularies]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Classes]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Classes]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Examples]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Examples]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Illustration]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Illustration]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Interpretations]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Interpretations]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pronunciation]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pronunciation]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[System]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [System]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Vocabularies]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Vocabularies]
GO

/* Create Tables */

CREATE TABLE [Categories]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[name] nvarchar(128) NOT NULL,
	[title] nvarchar(128) NOT NULL,
	[parent] bigint NULL DEFAULT 0
)
GO

CREATE TABLE [CategorizedVocabularies]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[hierarchical_category_id] bigint NOT NULL,
	[class] bigint NOT NULL,
	[vocabulary] nvarchar(128) NOT NULL
)
GO

CREATE TABLE [Classes]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[name] nvarchar(128) NOT NULL,
	[title] nvarchar(128) NOT NULL
)
GO

CREATE TABLE [Examples]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[interpretation_id] bigint NOT NULL,
	[example] nvarchar(512) NOT NULL,
	[translation] nvarchar(512) NOT NULL
)
GO

CREATE TABLE [Illustration]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[class] bigint NOT NULL,
	[vocabulary] nvarchar(128) NOT NULL,
	[interpretation_id] bigint NULL,
	[type] tinyint NOT NULL,
	[url] nvarchar(512) NOT NULL
)
GO

CREATE TABLE [Interpretations]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[class] bigint NOT NULL,
	[vocabulary] nvarchar(128) NOT NULL,
	[interpretation] nvarchar(128) NOT NULL
)
GO

CREATE TABLE [Pronunciation]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[class] bigint NOT NULL,
	[vocabulary] nvarchar(128) NOT NULL,
	[pronounciation] nvarchar(128) NOT NULL,
	[audio_path] nvarchar(512) NULL
)
GO

CREATE TABLE [System]
(
	[name] nvarchar(128) NOT NULL,
	[version] bigint NOT NULL,
	[desc] nvarchar(128) NULL,
	[pin] varchar(128) NOT NULL,    -- Pass-code
	[date] int NOT NULL
)
GO

CREATE TABLE [Vocabularies]
(
	[name] nvarchar(128) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Categories] 
 ADD CONSTRAINT [PK_Categories]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Categories] 
 ADD CONSTRAINT [UQ_Categories_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Categories] 
 ADD CONSTRAINT [UQ_Categories_name] UNIQUE NONCLUSTERED ([name] ASC)
GO

ALTER TABLE [Categories] 
 ADD CONSTRAINT [UQ_Categories_title] UNIQUE NONCLUSTERED ([title] ASC)
GO

ALTER TABLE [CategorizedVocabularies] 
 ADD CONSTRAINT [PK_CategorizedVocabularies]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [CategorizedVocabularies] 
 ADD CONSTRAINT [UQ_CategorizedVocabularies_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Classes] 
 ADD CONSTRAINT [PK_Classes]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Classes] 
 ADD CONSTRAINT [UQ_Classes_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Classes] 
 ADD CONSTRAINT [UQ_Classes_name] UNIQUE NONCLUSTERED ([name] ASC)
GO

ALTER TABLE [Classes] 
 ADD CONSTRAINT [UQ_Classes_title] UNIQUE NONCLUSTERED ([title] ASC)
GO

ALTER TABLE [Examples] 
 ADD CONSTRAINT [PK_Examples]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Examples] 
 ADD CONSTRAINT [UQ_Examples_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Illustration] 
 ADD CONSTRAINT [PK_Illustration]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Illustration] 
 ADD CONSTRAINT [UQ_Illustration_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Interpretations] 
 ADD CONSTRAINT [PK_Interpretations]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Interpretations] 
 ADD CONSTRAINT [UQ_Interpretations_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Pronunciation] 
 ADD CONSTRAINT [PK_Pronunciation]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Pronunciation] 
 ADD CONSTRAINT [UQ_Pronunciation_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Pronunciation] 
 ADD CONSTRAINT [UQ_Pronunciation_pronounciation] UNIQUE NONCLUSTERED ([pronounciation] ASC)
GO

ALTER TABLE [System] 
 ADD CONSTRAINT [UQ_System_name] UNIQUE NONCLUSTERED ([name] ASC)
GO

ALTER TABLE [System] 
 ADD CONSTRAINT [UQ_System_version] UNIQUE NONCLUSTERED ([version] ASC)
GO

ALTER TABLE [Vocabularies] 
 ADD CONSTRAINT [PK_Vocabularies]
	PRIMARY KEY CLUSTERED ([name] ASC)
GO

ALTER TABLE [Vocabularies] 
 ADD CONSTRAINT [UQ_Vocabularies] UNIQUE NONCLUSTERED ([name] ASC)
GO

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'System information','Schema', [dbo], 'table', [System]
GO

EXEC sp_addextendedproperty 'MS_Description', 'Pass-code', 'Schema', [dbo], 'table', [System], 'column', [pin]
GO
