/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 17-May-2019 11:58:31 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

USE [EnglishStudyPro]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[HierarchicalCategories]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [HierarchicalCategories]
GO

/* Create Tables */

CREATE TABLE [HierarchicalCategories]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[category] bigint NOT NULL,
	[parent_category] bigint NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [HierarchicalCategories] 
 ADD CONSTRAINT [PK_HierarchicalCategories]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [HierarchicalCategories] 
 ADD CONSTRAINT [UQ_HierarchicalCategories_id] UNIQUE NONCLUSTERED ([id] ASC)
GO
