/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 18-May-2019 1:58:34 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

USE [EnglishStudyPro]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Illustration]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Illustration]
GO

/* Create Tables */

CREATE TABLE [Illustration]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[class] bigint NOT NULL,
	[vocabulary] nvarchar(128) NOT NULL,
	[interpretation_id] bigint NULL,
	[type] tinyint NOT NULL,
	[url] nvarchar(512) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Illustration] 
 ADD CONSTRAINT [PK_Illustration]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Illustration] 
 ADD CONSTRAINT [UQ_Illustration_id] UNIQUE NONCLUSTERED ([id] ASC)
GO