/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 18-May-2019 1:58:34 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

USE [EnglishStudyPro]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Pronunciation]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Pronunciation]
GO

/* Create Tables */

CREATE TABLE [Pronunciation]
(
	[id] bigint NOT NULL IDENTITY (1, 1),
	[class] bigint NOT NULL,
	[vocabulary] nvarchar(128) NOT NULL,
	[pronounciation] nvarchar(128) NOT NULL,
	[audio_path] nvarchar(512) NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Pronunciation] 
 ADD CONSTRAINT [PK_Pronunciation]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Pronunciation] 
 ADD CONSTRAINT [UQ_Pronunciation_id] UNIQUE NONCLUSTERED ([id] ASC)
GO

ALTER TABLE [Pronunciation] 
 ADD CONSTRAINT [UQ_Pronunciation_pronounciation] UNIQUE NONCLUSTERED ([pronounciation] ASC)
GO