/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 18-May-2019 1:58:34 PM 				*/
/*  DBMS       : SQL Server 2008 						*/
/* ---------------------------------------------------- */

USE [EnglishStudyPro]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Vocabularies]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Vocabularies]
GO

/* Create Tables */

CREATE TABLE [Vocabularies]
(
	[name] nvarchar(128) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Vocabularies] 
 ADD CONSTRAINT [PK_Vocabularies]
	PRIMARY KEY CLUSTERED ([name] ASC)
GO

ALTER TABLE [Vocabularies] 
 ADD CONSTRAINT [UQ_Vocabularies] UNIQUE NONCLUSTERED ([name] ASC)
GO